apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\jordy\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\jordy\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/ciri2-ciri2-network: "true"
        io.kompose.service: influxdb
    spec:
      containers:
        - env:
            - name: INFLUXDB_ADMIN_PASSWORD
              value: supersecretpassword
            - name: INFLUXDB_ADMIN_USER
              value: admin
            - name: INFLUXDB_DB
              value: krakend
            - name: INFLUXDB_USER
              value: krakend-dev
            - name: INFLUXDB_USER_PASSWORD
              value: pas5w0rd
          image: influxdb:1.8.10
          name: influxdb
          ports:
            - containerPort: 8086
              hostPort: 8086
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
