apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\jordy\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: pc-microservice
  name: pc-microservice
spec:
  ports:
    - name: '4050'
      port: 4050
      targetPort: 4050
  selector:
    io.kompose.service: pc-microservice
status:
  loadBalancer: {}
