apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\jordy\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
    - name: '27017'
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
