name: Release

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      # Setup pnpm
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set Git identity
        run: |
          git config --global user.name "GitHub Actions Versioning"
          git config --global user.email "versioning@version.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/CIRI2-s6/ciri2-app.git

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go version

      # Setup nodejs
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # Install dependencies
      - name: Install dependencies
        run: pnpm install
      - name: Install nx
        run: pnpm install -g nx

      - name: Semantic versioning
        run: pnpm run version:affected
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Tag last-release
        shell: bash
        run: |
          git tag -f last-release
          git push origin last-release --force
