name: Development
# run on every push
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      # Setup pnpm
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go version
      - name: Set Git identity
        run: |
          git config --global user.name "GitHub Actions Versioning"
          git config --global user.email "versioning@version.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/CIRI2-s6/ciri2-app.git
      # Setup nodejs
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      # Install dependencies
      - name: Install dependencies
        run: pnpm install
      - name: Install nx
        run: pnpm install -g nx
      # Get the name of the application from the tag
      - name: Get application name from tag
        id: get_tag
        run: |
          TAG_NAME=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')
          APP_NAME=$(echo "${TAG_NAME}" | awk -F'-' '{print $1}')
          echo "::set-output name=app_name::${APP_NAME}"
      - name: Build application
        run: nx build "${{ steps.get_tag.outputs.app_name }}"
      - name: Dockerhub application
        run: nx docker "${{ steps.get_tag.outputs.app_name }}"
